[googleAnalytics]
  anonymizeIP = true
  respectDoNotTrack = true
  useSessionStorage = false
[instagram]
  simple = false
[x]
  enableDNT = true
[twitter]
  simple = false
[youtube]
  privacyEnhanced = true
